<?php

if(
	strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) !== 'xmlhttprequest' &&
	!preg_match('#^\/bitrix\/#', $_SERVER['REQUEST_URI'])
) {
	$redirect = false;
	$redirectSeo = false;
	$protocolChange = false;
	$dopRedirect = false;
	
	$sUrl = $_SERVER["REQUEST_URI"];
	$ar301 = [
		'/okno-odnostvorchatoe/' => '/',
		'/okno-odnostvorchatoe-odin/' => '/',
		'/formy-oplaty/' => '/',
		'/partnery/' => '/',
		'/vopros-otvet/' => '/',
		'/comparision/' => '/',
		'/my-nashli-reshenie/' => '/',
		'/sravnit-dve-sistemy/' => '/',
		'/vashi-priemuschestva/' => '/',
		'/v-bazovoy-komplektatsii/' => '/',
		'/-v-maksimalnoy-komplektatsii/' => '/',
		'/v-uluchshennoy-komplektatsii/' => '/',
		'/dveri-razdw/' => '/',
		'/dveri-vhodnye/' => '/',
		'/catalog/categories/' => '/',
		'/sertifikaty/' => '/about/',
		'/contacts/index/' => '/contacts/',
		'/map/' => '/contacts/',
		'/rassrochka/' => '/installment-plan/',
		'/halva-/' => '/installment-plan/',
		'/call/' => '/prices/',
		'/okna-pvh-ceny/' => '/prices/',
		'/aktsiya/' => '/promotions/',
		'/lamination/' => '/promotions/',
		'/aktsii/' => '/promotions/',
		'/reviews' => '/reviews/',
		'/reviews/index' => '/reviews/',
		'/nashi-raboty/' => '/reviews/',
		'/nedorogaja_ustanovka_okon_pvh/' => '/services/',
		'/servis/' => '/services/',
		'/diagnostika-mikroklimata/' => '/services/',
		'/montazh-po-gostu/' => '/services/',
		'/ustanovka-i-montazh-okon-pvh/' => '/services/',
		'/dileram/' => '/to-dealers/',
		'/articles/' => '/useful-information/',
		'/posts/index/' => '/useful-information/',
		'/product/razdvizhnye-sistemy/' => '/',
		'/product/raspashnye-sistemy/' => '/',
		'/product/-v-maksimalnoy-komplektatsii/' => '/windows-albinos/',
		'/product/v-uluchshennoy-komplektatsii/' => '/windows-albinos/',
		'/product/v-bazovoy-komplektatsii/' => '/windows-albinos/',
		'/minus-20-minus-30/' => '/promotions/',
		'/solutions/premium/' => '/windows-albinos/',
		'/solutions/medium/' => '/windows-albinos/',
		'/solutions/light/' => '/windows-albinos/',
		'/teplosberegajuwie-okna/' => '/useful-information/teplosberegayuschie-okna/',
		'/shumoizolirujuwie-svojstva-steklopaketa/' => '/useful-information/shumoizoliruyuschie-svoystva-steklopaketa/',
		'/comments/' => '/reviews/',
		'/5-kriteriev-vybora-furnitury/' => '/useful-information/okna-i-steklopakety-5-kriteriev-vybora-furniturnoy-sistemy/',
		'/certificates/' => '/about/',
		'/kontakty/' => '/contacts/',
		'/kontakty/okna-pvh-bobruisk/' => '/contacts/',
		'/kontakty/okna-pvh-baranovichi/' => '/contacts/',
		'/kontakty/okna-pvh-soligorsk/' => '/contacts/',
		'/kontakty/okna-pvh-borisov/' => '/contacts/',
		'/kontakty/okna-pvh-dzerjinsk/' => '/contacts/',
		'/kontakty/okna-pvh-jlobin/' => '/contacts/',
		'/kontakty/okna-pvh-jodino/' => '/contacts/',
		'/kontakty/okna-pvh-rechtsa/' => '/contacts/',
		'/okna-pvh-brest_polotsk-novopolotsk/' => '/contacts/',
		'/kontakty/okna-pvh-mogilev/' => '/contacts/',
		'/kontakty/okna-pvh-grodno/' => '/contacts/',
		'/kontakty/okna-pvh-gomel/' => '/contacts/',
		'/kontakty/okna-pvh-brest/' => '/contacts/',
		'/kontakty/okna-pvh-vitebsk/' => '/contacts/',
		'/kontakty/okna-pvh-minsk/' => '/contacts/',
		'/about/okna_pvh_ustanovka/' => '/services/',
		'/about/partnery/' => '/about/',
		'/about/works/' => '/reviews/',
		'/about/comment/' => '/reviews/',
		'/about/faqs/' => '/',
		'/about/sertificates/' => '/about/',
		'/okna-pvh-ceny/okna_pvh_v_rassrochku/' => '/installment-plan/',
		'/okna-pvh-ceny/oplati/' => '/installment-plan/',
		'/okna-pvh-ceny/akciy/' => '/promotions/',
		'/servicea/service/' => '/services/',
		'/servicea/mikroklimat/' => '/services/',
		'/servicea/' => '/services/',
		'/balkon/balcony_compare/' => '/',
		'/balkon/swing/' => '/',
		'/balkon/' => '/',
		'/about/ustanovka_montage/' => '/services/',
		'/solutions/comparision/' => '/windows-albinos/',
		'/posts/show/ceny-na-okna-pvh-v-mar\'inoj-gorke/' => '/useful-information/ceny-na-okna-pvh-v-marinoj-gorke/',
		'/posts/show/rassrochka-na-okna-pvh-v-mar\'inoj-gorke/' => '/useful-information/rassrochka-na-okna-pvh-v-marinoj-gorke/',
		'/posts/show/stoimost\'-okon-pvh-v-gorkah/' => '/useful-information/stoimost-okon-pvh-v-gorkah/',
		'/posts/show/kal\'kuljator-okon-pvh-v-vitebske/' => '/useful-information/kalkuljator-okon-pvh-v-vitebske/',
		'/posts/show/kal\'kuljator-okon-pvh-v-breste/' => '/useful-information/kalkuljator-okon-pvh-v-breste/',
		'/ustanovka-okon-pvh/' => '/services/',
		'/proizvodstvo-okon-pvh/' => '/useful-information/proizvodstvo-plastikovyh-okon/',
		'/step-4/' => '/',
		'/aluminium.htm/' => '/',
		'/glass_pack.htm/' => '/',
		'/index.htm/' => '/',
		'/price.htm/' => '/prices/',
		'/zolotye-gody/' => '/promotions/',
		'/articles/~shownews/article37/' => '/useful-information/',
		'/posts/show/752-kupit-okna-pvh-v-minske-v-rassrochku-po-halve/' => '/useful-information/',
		'/kupit-okna-pvh-v-soligorske/' => '/contacts/',
		'/ivatsevichi/' => '/contacts/',
		'/braslav/' => '/contacts/',
		'/loev/' => '/contacts/',
		'/galleries/' => '/',
		'/rossony/' => '/contacts/',
		'/gorki/' => '/contacts/',
		'/nesvizh/' => '/contacts/',
		'/cherikov/' => '/contacts/',
		'/kupit-okna-pvh-v-rechitse/' => '/contacts/',
		'/verhnedvinsk/' => '/contacts/',
		'/fanipol/' => '/contacts/',
		'/kupit-okna-pvh-v-gomele/' => '/contacts/',
		'/kupit-okna-pvh-v-baranovichah/' => '/contacts/',
		'/kupit-okna-pvh-v-polotske-i-novopoltske/' => '/contacts/',
		'/category/okna/' => '/windows-albinos/',
		'/kupit-okna-pvh-v-zhlobine/' => '/contacts/',
		'/kletsk/' => '/contacts/',
		'/kupit-okna-pvh-v-mogileve/' => '/contacts/',
		'/kupit-okna-pvh-v-grodno/' => '/contacts/',
		'/pinsk/' => '/contacts/',
		'/lyahovichi/' => '/contacts/',
		'/dribin/' => '/contacts/',
		'/kupit-okna-pvh-v-dzerzhinske/' => '/contacts/',
		'/zaslavl/' => '/contacts/',
		'/aktsiya-50/' => '/promotions/',
		'/bogushevsk/' => '/contacts/',
		'/slonim/' => '/contacts/',
		'/ivanovo/' => '/contacts/',
		'/starye-dorogi/' => '/contacts/',
		'/rakov/' => '/contacts/',
		'/krichev/' => '/contacts/',
		'/kobrin/' => '/contacts/',
		'/kamenets/' => '/contacts/',
		'/ivie/' => '/contacts/',
		'/gresk/' => '/contacts/',
		'/gorodok/' => '/contacts/',
		'/gorodeya/' => '/contacts/',
		'/glubokoe/' => '/contacts/',
		'/gantsevichi/' => '/contacts/',
		'/dubrovno/' => '/contacts/',
		'/drogichin/' => '/contacts/',
		'/dobrush/' => '/contacts/',
		'/disna/' => '/contacts/',
		'/chechersk/' => '/contacts/',
		'/chausy/' => '/contacts/',
		'/byhov/' => '/contacts/',
		'/buda-kashel-va/' => '/contacts/',
		'/beshenkovichi/' => '/contacts/',
		'/berezino/' => '/contacts/',
		'/baran/' => '/contacts/',
		'/mstislavl/' => '/contacts/',
		'/miory/' => '/contacts/',
		'/marina-gorka/' => '/contacts/',
		'/malorita/' => '/contacts/',
		'/lyuban/' => '/contacts/',
		'/logoysk/' => '/contacts/',
		'/liozno/' => '/contacts/',
		'/lida/' => '/contacts/',
		'/kupit-okna-pvh-v-zhodino/' => '/contacts/',
		'/kupit-okna-pvh-v-vitebske/' => '/contacts/',
		'/kupit-okna-pvh-v-minske/' => '/contacts/',
		'/kupit-okna-pvh-v-breste/' => '/contacts/',
		'/kupit-okna-pvh-v-borisove/' => '/contacts/',
		'/zhabinka/' => '/contacts/',
		'/voronovo/' => '/contacts/',
		'/vetka/' => '/contacts/',
		'/ushachi/' => '/contacts/',
		'/tolochin/' => '/contacts/',
		'/telehany/' => '/contacts/',
		'/svetlogorsk/' => '/contacts/',
		'/slutsk/' => '/contacts/',
		'/slavgorod/' => '/contacts/',
		'/skidel/' => '/contacts/',
		'/shumilino/' => '/contacts/',
		'/sharkoschina/' => '/contacts/',
		'/senno/' => '/contacts/',
		'/schuchin/' => '/contacts/',
		'/rudensk/' => '/contacts/',
		'/rogach-v/' => '/contacts/',
		'/radoshkovichi/' => '/contacts/',
		'/orsha/' => '/contacts/',
		'/useful-information/vidy-razdvizhnyh-balkonnyh-ram-new/' => '/useful-information/vidy-razdvizhnyh-balkonnyh-ram/',
		'/posts/show/663-7-sovetov-po-vyboru-ustanovschika-okon-pvh/' => '/useful-information/7-sovetov-po-vyboru-ustanovschika-okon-pvh/',
		'/posts/show/akcii-na-okna-pvh-v-slucke/' => '/useful-information/akcii-na-okna-pvh-v-slucke/',
		'/posts/show/770-aktsiya-na-balkonnye-okna-pvh-v-minske-tseny/' => '/useful-information/aktsiya-na-balkonnye-okna-pvh-v-minske-tseny/',
		'/posts/show/833-balkonnyy-blok-pvh-v-minske-tsena-na-balkonnyy-blok/' => '/useful-information/balkonnyy-blok-pvh-v-minske-tsena-na-balkonnyy-blok/',
		'/posts/show/ceny-na-okna-pvh-v-marinoj-gorke/' => '/useful-information/ceny-na-okna-pvh-v-marinoj-gorke/',
		'/posts/show/655-chem-grozit-nenadezhnoe-armirovanie/' => '/useful-information/chem-grozit-nenadezhnoe-armirovanie/',
		'/posts/show/632-chto-delat-esli-zaklinilo-plastikovoe-okno/' => '/useful-information/chto-delat-esli-zaklinilo-plastikovoe-okno/',
		'/posts/show/560-chto-takoe-laminirovannyy-profil-pvh-/' => '/useful-information/chto-takoe-laminirovannyy-profil-pvh/',
		'/posts/show/720-chto-takoe-steklopaket-i-kakoy-iz-nih-luchshe/' => '/useful-information/chto-takoe-steklopaket-i-kakoy-iz-nih-luchshe/',
		'/posts/show/615-chto-vliyaet-na-tsenu-plastikovogo-okna-kak-vybrat-okno-pvh-/' => '/useful-information/chto-vliyaet-na-tsenu-plastikovogo-okna-kak-vybrat-okno-pvh/',
		'/posts/show/548-derevyannye-ili-plastikovye-okna-chto-vybrat/' => '/useful-information/derevyannye-ili-plastikovye-okna-chto-vybrat/',
		'/posts/show/714-deshevye-okna-pvh-dlya-dachi-gde-kupit-dachnye-okna-v-minske/' => '/useful-information/deshevye-okna-pvh-dlya-dachi-gde-kupit-dachnye-okna-v-minske/',
		'/posts/show/667-deti-i-okna/' => '/useful-information/deti-i-okna/',
		'/posts/show/498-dorogie-okna-ili-okna-podeshevle-/' => '/useful-information/dorogie-okna-ili-okna-podeshevle/',
		'/posts/show/816-dveri-so-steklopaketom-v-minske-tseny-na-dveri-so-steklopaketom/' => '/useful-information/dveri-so-steklopaketom-v-minske-tseny-na-dveri-so-steklopaketom/',
		'/posts/show/736-ekologicheski-chistye-okna-pvh/' => '/useful-information/ekologicheski-chistye-okna-pvh/',
		'/posts/show/614-ekologicheski-chistye-plastikovye-okna/' => '/useful-information/ekologicheski-chistye-plastikovye-okna/',
		'/posts/show/650-energosberegayuschie-okna/' => '/useful-information/energosberegayuschie-okna/',
		'/posts/show/635-furnitura-dlya-okon-pvh/' => '/useful-information/furnitura-dlya-okon-pvh/',
		'/posts/show/656-furn-tura-dlya-plastykavaga-akna/' => '/useful-information/furnitura-dlya-plastykavaga-akna/',
		'/posts/show/733-kachestvennye-i-nedorogie-okna-pvh-v-minske/' => '/useful-information/kachestvennye-i-nedorogie-okna-pvh-v-minske/',
		'/posts/show/646-kak-demontirovat-staroe-okno-samostoyatelno/' => '/useful-information/kak-demontirovat-staroe-okno-samostoyatelno/',
		'/posts/show/555-kakie-funktsii-furnitury-oblegchayut-nam-zhizn-/' => '/useful-information/kakie-funktsii-furnitury-oblegchayut-nam-zhizn/',
		'/posts/show/731-kakie-okna-pvh-luchshe-vybrat-dlya-kvartiry/' => '/useful-information/kakie-okna-pvh-luchshe-vybrat-dlya-kvartiry/',
		'/posts/show/540-kakie-plastikovye-okna-luchshe-/' => '/useful-information/kakie-plastikovye-okna-luchshe/',
		'/posts/show/564-kak-ne-oshibitsya-pri-vybore-prodavtsa-plastikovyh-okon-/' => '/useful-information/kak-ne-oshibitsya-pri-vybore-prodavtsa-plastikovyh-okon/',
		'/posts/show/715-kak-osteklit-balkon-nedorogo/' => '/useful-information/kak-osteklit-balkon-nedorogo/',
		'/posts/show/717-kak-osteklit-balkon-nedorogo/' => '/useful-information/kak-osteklit-balkon-nedorogo/',
		'/posts/show/732-kak-osteklit-kuhnyu-nedorogo/' => '/useful-information/kak-osteklit-kuhnyu-nedorogo/',
		'/posts/show/515-kak-osteklitsya-i-ne-oshibitsya/' => '/useful-information/kak-osteklitsya-i-ne-oshibitsya/',
		'/posts/show/729-kak-pravilno-vybrat-okna-dlya-detskoy/' => '/useful-information/kak-pravilno-vybrat-okna-dlya-detskoy/',
		'/posts/show/539-kak-pravilno-zakazat-plastikovye-okna-/' => '/useful-information/kak-pravilno-zakazat-plastikovye-okna/',
		'/posts/show/543-kak-prohodit-raschet-stoimosti-pvh-okna-plastikovogo-okna-/' => '/useful-information/kak-prohodit-raschet-stoimosti-pvh-okna-plastikovogo-okna/',
		'/posts/show/678-kak-sdelat-iz-balkona-ofis/' => '/useful-information/kak-sdelat-iz-balkona-ofis/',
		'/posts/show/660-kak-sekonomit-na-dachnom-osteklenii-/' => '/useful-information/kak-sekonomit-na-dachnom-osteklenii/',
		'/posts/show/563-kak-uhazhivat-za-laminirovannymi-oknami-/' => '/useful-information/kak-uhazhivat-za-laminirovannymi-oknami/',
		'/posts/show/645-kak-ustanovit-plastikovoe-okno/' => '/useful-information/kak-ustanovit-plastikovoe-okno/',
		'/posts/show/651-kak-uteplit-balkon-iznutri/' => '/useful-information/kak-uteplit-balkon-iznutri/',
		'/posts/show/734-kak-vybrat-okno-v-detskuyu-komnatu/' => '/useful-information/kak-vybrat-okno-v-detskuyu-komnatu/',
		'/posts/show/721-kak-vybrat-plastikovoe-okno-na-kuhnyu-nedorogo/' => '/useful-information/kak-vybrat-plastikovoe-okno-na-kuhnyu-nedorogo/',
		'/posts/show/613-kak-vybrat-plastikovoe-okno-v-detskuyu/' => '/useful-information/kak-vybrat-plastikovoe-okno-v-detskuyu/',
		'/posts/show/626-kak-vybrat-plastikovoe-okno-v-spalnyu/' => '/useful-information/kak-vybrat-plastikovoe-okno-v-spalnyu/',
		'/posts/show/723-kak-vybrat-plastikovye-okna/' => '/useful-information/kak-vybrat-plastikovye-okna/',
		'/posts/show/565-kak-vybrat-steklopaket/' => '/useful-information/kak-vybrat-steklopaket/',
		'/posts/show/719-kak-vybrat-teplye-okna-dlya-dachi/' => '/useful-information/kak-vybrat-teplye-okna-dlya-dachi/',
		'/posts/show/633-kak-zaschitit-rebenka-ot-padeniya-iz-okna/' => '/useful-information/kak-zaschitit-rebenka-ot-padeniya-iz-okna/',
		'/posts/show/kalkuljator-okon-pvh-v-breste/' => '/useful-information/kalkuljator-okon-pvh-v-breste/',
		'/posts/show/kalkuljator-okon-pvh-v-vitebske/' => '/useful-information/kalkuljator-okon-pvh-v-vitebske/',
		'/posts/show/738-kalkulyator-rascheta-plastikovyh-okon-pvh-v-minske-kalkulyator-okon-pvh-onlayn/' => '/useful-information/kalkulyator-rascheta-plastikovyh-okon-pvh-v-minske-kalkulyator-okon-pvh-onlayn/',
		'/posts/show/737-kalkulyator-tsen/' => '/useful-information/kalkulyator-tsen/',
		'/posts/show/516-kogda-montazh-ne-nash/' => '/useful-information/kogda-montazh-ne-nash/',
		'/posts/show/547-kondensat-na-plastikovyh-oknah-prichiny-poyavleniya-i-sposoby-ustraneniya/' => '/useful-information/kondensat-na-plastikovyh-oknah-prichiny-poyavleniya-i-sposoby-ustraneniya/',
		'/posts/show/517-kratkaya-okonnaya-shpargalka-v-pomosch-zakazchiku/' => '/useful-information/kratkaya-okonnaya-shpargalka-v-pomosch-zakazchiku/',
		'/posts/show/518-kto-obidel-okna-/' => '/useful-information/kto-obidel-okna/',
		'/posts/show/754-kupit-deshevye-okna-pvh-v-minske-tseny-na-deshevye-plastikovye-okna/' => '/useful-information/kupit-deshevye-okna-pvh-v-minske-tseny-na-deshevye-plastikovye-okna/',
		'/posts/show/785-kupit-deshevye-pvh-okna-v-molodechno/' => '/useful-information/kupit-deshevye-pvh-okna-v-molodechno/',
		'/posts/show/757-kupit-dveri-okna-pvh-v-minske-tseny-na-ustanovku-okon-dverey-pvh/' => '/useful-information/kupit-dveri-okna-pvh-v-minske-tseny-na-ustanovku-okon-dverey-pvh/',
		'/posts/show/768-kupit-energosberegayuschie-plastikovye-okna-tseny-i-stoimost-na-teplye-okna-pvh-s-energosberegayuschim-steklom/' => '/useful-information/kupit-energosberegayuschie-plastikovye-okna-tseny-i-stoimost-na-teplye-okna-pvh-s-energosberegayuschim-steklom/',
		'/posts/show/865-kupit-frantsuzskie-okna-v-minske-tseny-na-frantsuzskoe-okno-foto-frantsuzskih-okon/' => '/useful-information/kupit-frantsuzskie-okna-v-minske-tseny-na-frantsuzskoe-okno-foto-frantsuzskih-okon/',
		'/posts/show/756-kupit-gotovye-okna-pvh-dlya-dachi-na-rasprodazhe-v-minske/' => '/useful-information/kupit-gotovye-okna-pvh-dlya-dachi-na-rasprodazhe-v-minske/',
		'/posts/show/751-kupit-gotovye-okna-pvh-po-aktsii-v-minske-tseny-na-okna-pvh-skidki/' => '/useful-information/kupit-gotovye-okna-pvh-po-aktsii-v-minske-tseny-na-okna-pvh-skidki/',
		'/posts/show/850-kupit-gotovye-steklopakety-v-minske-tsena-na-gotovye-steklopakety/' => '/useful-information/kupit-gotovye-steklopakety-v-minske-tsena-na-gotovye-steklopakety/',
		'/posts/show/730-kupit-kachestvennye-i-nedorogie-okna/' => '/useful-information/kupit-kachestvennye-i-nedorogie-okna/',
		'/posts/show/758-kupit-mansardnye-okna-v-minske-tseny-na-mansardnye-okna/' => '/useful-information/kupit-mansardnye-okna-v-minske-tseny-na-mansardnye-okna/',
		'/posts/show/741-kupit-okna-na-kuhnyu-v-minske-tseny-na-okna-dlya-kuhni/' => '/useful-information/kupit-okna-na-kuhnyu-v-minske-tseny-na-okna-dlya-kuhni/',
		'/posts/show/755-kupit-okna-pvh-dlya-dachi-deshevo-v-minske/' => '/useful-information/kupit-okna-pvh-dlya-dachi-deshevo-v-minske/',
		'/posts/show/774-kupit-okna-pvh-v-rassrochku-bez-pervonachalnogo-vznosa-v-minske/' => '/useful-information/kupit-okna-pvh-v-rassrochku-bez-pervonachalnogo-vznosa-v-minske/',
		'/posts/show/753-kupit-okna-pvh-v-rassrochku-na-12-mesyatsev-v-minske/' => '/useful-information/kupit-okna-pvh-v-rassrochku-na-12-mesyatsev-v-minske/',
		'/posts/show/771-kupit-okna-s-balkonnoy-dveryu-v-minske/' => '/useful-information/kupit-okna-s-balkonnoy-dveryu-v-minske/',
		'/posts/show/742-kupit-okno-spalni-v-minske-tseny-na-okna-spalni/' => '/useful-information/kupit-okno-spalni-v-minske-tseny-na-okna-spalni/',
		'/posts/show/820-kupit-plastikovye-okna-v-borisove-tseny-na-okna-pvh/' => '/useful-information/kupit-plastikovye-okna-v-borisove-tseny-na-okna-pvh/',
		'/posts/show/807-kupit-pvh-okna-v-baranovichah-tseny-na-pvh-okna-/' => '/useful-information/kupit-pvh-okna-v-baranovichah-tseny-na-pvh-okna/',
		'/posts/show/829-kupit-pvh-okna-v-belarusi-tseny-na-okna-pvh-v-rb/' => '/useful-information/kupit-pvh-okna-v-belarusi-tseny-na-okna-pvh-v-rb/',
		'/posts/show/867-kupit-pvh-okna-v-bobruyske-tseny-na-okna-pvh-v-bobruyske/' => '/useful-information/kupit-pvh-okna-v-bobruyske-tseny-na-okna-pvh-v-bobruyske/',
		'/posts/show/778-kupit-pvh-okna-v-breste/' => '/useful-information/kupit-pvh-okna-v-breste/',
		'/posts/show/776-kupit-pvh-okna-v-gomele-po-rassrochke-bez-pervonachalnogo-vznosa/' => '/useful-information/kupit-pvh-okna-v-gomele-po-rassrochke-bez-pervonachalnogo-vznosa/',
		'/posts/show/779-kupit-pvh-okna-v-gomele-tseny-na-plastikovye-okna/' => '/useful-information/kupit-pvh-okna-v-gomele-tseny-na-plastikovye-okna/',
		'/posts/show/790-kupit-pvh-okna-v-grodno-tseny-na-plastikovye-okna/' => '/useful-information/kupit-pvh-okna-v-grodno-tseny-na-plastikovye-okna/',
		'/posts/show/775-kupit-pvh-okna-v-mogileve-tseny-i-rastsenki-na-plastikovye-okna/' => '/useful-information/kupit-pvh-okna-v-mogileve-tseny-i-rastsenki-na-plastikovye-okna/',
		'/posts/show/804-kupit-pvh-okna-v-mogileve-v-rassrochku-tseny-na-pvh-okna-v-rassrochku/' => '/useful-information/kupit-pvh-okna-v-mogileve-v-rassrochku-tseny-na-pvh-okna-v-rassrochku/',
		'/posts/show/786-kupit-pvh-okna-v-molodechno-tseny-na-plastikovye-okna/' => '/useful-information/kupit-pvh-okna-v-molodechno-tseny-na-plastikovye-okna/',
		'/posts/show/782-kupit-pvh-okna-v-mozyre/' => '/useful-information/kupit-pvh-okna-v-mozyre/',
		'/posts/show/740-kupit-pvh-okna-v-rassrochku-v-minske-tseny-na-plastikovye-okna-v-rassrochku/' => '/useful-information/kupit-pvh-okna-v-rassrochku-v-minske-tseny-na-plastikovye-okna-v-rassrochku/',
		'/posts/show/827-kupit-pvh-okna-v-slutske-tseny-na-pvh-okna-po-aktsii/' => '/useful-information/kupit-pvh-okna-v-slutske-tseny-na-pvh-okna-po-aktsii/',
		'/posts/show/783-kupit-pvh-okna-v-smolenske/' => '/useful-information/kupit-pvh-okna-v-smolenske/',
		'/posts/show/784-kupit-pvh-okna-v-smolevichah/' => '/useful-information/kupit-pvh-okna-v-smolevichah/',
		'/posts/show/777-kupit-pvh-okna-v-soligorske-tseny-na-plastikovye-okna/' => '/useful-information/kupit-pvh-okna-v-soligorske-tseny-na-plastikovye-okna/',
		'/posts/show/803-kupit-pvh-okna-v-soligorske-v-rassrochku-tseny-na-pvh-okna-v-rassrochku/' => '/useful-information/kupit-pvh-okna-v-soligorske-v-rassrochku-tseny-na-pvh-okna-v-rassrochku/',
		'/posts/show/806-kupit-pvh-okna-v-zhodino-tseny-na-pvh-okna-/' => '/useful-information/kupit-pvh-okna-v-zhodino-tseny-na-pvh-okna/',
		'/posts/show/739-kupit-razdvizhnye-okna-na-balkon-v-minske-tseny-na-razdvizhnye-okna-dlya-balkona/' => '/useful-information/kupit-razdvizhnye-okna-na-balkon-v-minske-tseny-na-razdvizhnye-okna-dlya-balkona/',
		'/posts/show/781-kupit-steklopakety-v-mogileve/' => '/useful-information/kupit-steklopakety-v-mogileve/',
		'/posts/show/828-kupit-steklo-tripleks-v-minske-tseny-na-stekla-tripleks/' => '/useful-information/kupit-steklo-tripleks-v-minske-tseny-na-stekla-tripleks/',
		'/posts/show/773-kupit-trehstvorchatoe-okno-v-minske/' => '/useful-information/kupit-trehstvorchatoe-okno-v-minske/',
		'/posts/show/868-kupit-tsvetnoe-steklo-v-minske-tsvetnye-plastikovye-okna/' => '/useful-information/kupit-tsvetnoe-steklo-v-minske-tsvetnye-plastikovye-okna/',
		'/posts/show/510-kupit-v-rassrochku-ili-za-nalichnye-/' => '/useful-information/kupit-v-rassrochku-ili-za-nalichnye/',
		'/posts/show/764-kupit-zakalennoe-steklo-v-minske-tseny-na-zakalennye-stekla/' => '/useful-information/kupit-zakalennoe-steklo-v-minske-tseny-na-zakalennye-stekla/',
		'/posts/show/512-laminirovanie-tsvetnoe-reshenie-voprosa-okon-/' => '/useful-information/laminirovanie-tsvetnoe-reshenie-voprosa-okon/',
		'/posts/show/521-madmuazel-vashu-ruchku-/' => '/useful-information/madmuazel-vashu-ruchku/',
		'/posts/show/866-metalloplastikovye-okna-v-minske-tseny-na-metalloplastikovye-okna/' => '/useful-information/metalloplastikovye-okna-v-minske-tseny-na-metalloplastikovye-okna/',
		'/posts/show/527-mikrofunktsiya-s-makroznacheniem-ili-chto-takoe-mikroprovetrivanie/' => '/useful-information/mikrofunktsiya-s-makroznacheniem-ili-chto-takoe-mikroprovetrivanie/',
		'/posts/show/860-montazhnik-okon-pvh-v-minske/' => '/useful-information/montazhnik-okon-pvh-v-minske/',
		'/posts/show/558-montazh-okon-pvh-kriterii-kachestvennoy-ustanovki-plastikovyh-okon/' => '/useful-information/montazh-okon-pvh-kriterii-kachestvennoy-ustanovki-plastikovyh-okon/',
		'/posts/show/523-montazh-okon-sovershenstvo-v-detalyah-/' => '/useful-information/montazh-okon-sovershenstvo-v-detalyah/',
		'/posts/show/528-montazh-po-gostu-malenkie-sekrety-bolshogo-kachestva-/' => '/useful-information/montazh-po-gostu-malenkie-sekrety-bolshogo-kachestva/',
		'/posts/show/552-naibolee-chastye-oshibki-ustanovki-plastikovyh-okon/' => '/useful-information/naibolee-chastye-oshibki-ustanovki-plastikovyh-okon/',
		'/posts/show/495-na-okna-pvh-otzyvy-kakim-otzyvam-verit-a-kakim-ne-verit-po-sledam-dragotsennogo-opyta-/' => '/useful-information/na-okna-pvh-otzyvy-kakim-otzyvam-verit-a-kakim-ne-verit-po-sledam-dragotsennogo-opyta/',
		'/posts/show/530-nash-drug-balkon-/' => '/useful-information/nash-drug-balkon/',
		'/posts/show/519-nash-partner-fuhr/' => '/useful-information/nash-partner-fuhr/',
		'/posts/show/728-nedorogie-plastikovye-okna-dlya-dachi/' => '/useful-information/nedorogie-plastikovye-okna-dlya-dachi/',
		'/posts/show/514-ne-vse-plastikovye-profili-odinakovo-polezny/' => '/useful-information/ne-vse-plastikovye-profili-odinakovo-polezny/',
		'/posts/show/557-okna-i-steklopakety-5-kriteriev-vybora-furniturnoy-sistemy/' => '/useful-information/okna-i-steklopakety-5-kriteriev-vybora-furniturnoy-sistemy/',
		'/posts/show/503-okna-pvh-11-samyh-neobychnyh-faktov/' => '/useful-information/okna-pvh-11-samyh-neobychnyh-faktov/',
		'/posts/show/722-okna-pvh-dlya-kvartiry-v-uluchshennoy-komplektatsii/' => '/useful-information/okna-pvh-dlya-kvartiry-v-uluchshennoy-komplektatsii/',
		'/posts/show/500-okna-pvh-nedorogo-/' => '/useful-information/okna-pvh-nedorogo/',
		'/posts/show/501-okna-pvh-nedorogo-kupit-legko-platit-/' => '/useful-information/okna-pvh-nedorogo-kupit-legko-platit/',
		'/posts/show/504-okna-pvh-provodim-tender-na-kvartire/' => '/useful-information/okna-pvh-provodim-tender-na-kvartire/',
		'/posts/show/536-okna-pvh-rehau/' => '/useful-information/okna-pvh-rehau/',
		'/posts/show/502-okna-pvh-sekrety-vybora-/' => '/useful-information/okna-pvh-sekrety-vybora/',
		'/posts/show/491-okna-pvh-sovety-diletantu/' => '/useful-information/okna-pvh-sovety-diletantu/',
		'/posts/show/818-okna-pvh-v-borisove-tseny-na-okna-pvh-aktsiya-/' => '/useful-information/okna-pvh-v-borisove-tseny-na-okna-pvh-aktsiya/',
		'/posts/show/842-okna-pvh-v-borisove-v-rassrochku-tsena-na-okna-pvh-v-rassrochku/' => '/useful-information/okna-pvh-v-borisove-v-rassrochku-tsena-na-okna-pvh-v-rassrochku/',
		'/posts/show/okna-pvh-v-ljubani/' => '/useful-information/okna-pvh-v-ljubani/',
		'/posts/show/862-okna-pvh-v-logoyske-tsena-na-okna-pvh-v-logoyske/' => '/useful-information/okna-pvh-v-logoyske-tsena-na-okna-pvh-v-logoyske/',
		'/posts/show/843-okna-pvh-v-molodechno-v-rassrochku-tsena-na-okna-pvh-v-rassrochku/' => '/useful-information/okna-pvh-v-molodechno-v-rassrochku-tsena-na-okna-pvh-v-rassrochku/',
		'/posts/show/okna-pvh-v-nesvizhe/' => '/useful-information/okna-pvh-v-nesvizhe/',
		'/posts/show/861-okna-pvh-v-orshe-tsena-na-okna-pvh-v-orshe/' => '/useful-information/okna-pvh-v-orshe-tsena-na-okna-pvh-v-orshe/',
		'/posts/show/okna-pvh-v-piske/' => '/useful-information/okna-pvh-v-piske/',
		'/posts/show/542-okna-pvh-v-rassrochku-chto-eto-takoe-/' => '/useful-information/okna-pvh-v-rassrochku-chto-eto-takoe/',
		'/posts/show/821-okna-pvh-v-rechitse-tseny-na-pvh-okna/' => '/useful-information/okna-pvh-v-rechitse-tseny-na-pvh-okna/',
		'/posts/show/okna-pvh-v-slucke/' => '/useful-information/okna-pvh-v-slucke/',
		'/posts/show/863-okna-pvh-v-vileyke-tsena-na-okna-pvh-v-vileyke/' => '/useful-information/okna-pvh-v-vileyke-tsena-na-okna-pvh-v-vileyke/',
		'/posts/show/864-okna-pvh-v-zaslavle-tsena-na-okna-pvh-v-zaslavle/' => '/useful-information/okna-pvh-v-zaslavle-tsena-na-okna-pvh-v-zaslavle/',
		'/posts/show/841-okna-pvh-v-zhodino-v-rassrochku-tsena-na-okna-pvh-v-rassrochku/' => '/useful-information/okna-pvh-v-zhodino-v-rassrochku-tsena-na-okna-pvh-v-rassrochku/',
		'/posts/show/506-okna-teplee-na-12-/' => '/useful-information/okna-teplee-na-12/',
		'/posts/show/507-okno-na-kuhnyu-tsennye-prakticheskie-sovety/' => '/useful-information/okno-na-kuhnyu-tsennye-prakticheskie-sovety/',
		'/posts/show/562-osteklenie-balkonov-i-lodzhiy-kakoy-vid-ostekleniya-vybrat-/' => '/useful-information/osteklenie-balkonov-i-lodzhiy-kakoy-vid-ostekleniya-vybrat/',
		'/posts/show/561-osteklenie-balkonov-i-lodzhiy-sposoby-ostekleniya-i-materialy/' => '/useful-information/osteklenie-balkonov-i-lodzhiy-sposoby-ostekleniya-i-materialy/',
		'/posts/show/osteklenie-balkonov-v-vitebske/' => '/useful-information/osteklenie-balkonov-v-vitebske/',
		'/posts/show/666-osteklenie-zagorodnogo-doma/' => '/useful-information/osteklenie-zagorodnogo-doma/',
		'/posts/show/627-ot-chego-zavisit-srok-ekspluatatsii-okna-pvh/' => '/useful-information/ot-chego-zavisit-srok-ekspluatatsii-okna-pvh/',
		'/posts/show/554-ot-chego-zavisyat-tseny-na-plastikovye-okna-/' => '/useful-information/ot-chego-zavisyat-tseny-na-plastikovye-okna/',
		'/posts/show/647-otlichiya-plastikovyh-i-derevyannyh-okon/' => '/useful-information/otlichiya-plastikovyh-i-derevyannyh-okon/',
		'/posts/show/634-plastikovye-okna-dlya-dachi/' => '/useful-information/plastikovye-okna-dlya-dachi/',
		'/posts/show/644-plastikovye-okna-dlya-kvartiry/' => '/useful-information/plastikovye-okna-dlya-kvartiry/',
		'/posts/show/559-plastikovye-okna-pvh-razrushaem-mify/' => '/useful-information/plastikovye-okna-pvh-razrushaem-mify/',
		'/posts/show/648-plyusy-i-minusy-plastikovyh-okon/' => '/useful-information/plyusy-i-minusy-plastikovyh-okon/',
		'/posts/show/631-pochemu-na-plastikovyh-oknah-poyavlyaetsya-kondensat/' => '/useful-information/pochemu-na-plastikovyh-oknah-poyavlyaetsya-kondensat/',
		'/posts/show/662-pochemu-plastikovye-okna-stanovyatsya-populyarnee/' => '/useful-information/pochemu-plastikovye-okna-stanovyatsya-populyarnee/',
		'/posts/show/541-pochemu-plastikovye-okna-tak-populyarny-u-belorusov-/' => '/useful-information/pochemu-plastikovye-okna-tak-populyarny-u-belorusov/',
		'/posts/show/657-podgotovka-k-ustanovke-okon/' => '/useful-information/podgotovka-k-ustanovke-okon/',
		'/posts/show/544-pravila-ekspluatatsii-i-uhoda-za-plastikovymi-oknami/' => '/useful-information/pravila-ekspluatatsii-i-uhoda-za-plastikovymi-oknami/',
		'/posts/show/553-pravila-vybora-okon-pvh/' => '/useful-information/pravila-vybora-okon-pvh/',
		'/posts/show/492-pravilnaya-ustanovka-plastikovyh-okon-sekrety-zimnego-montazha-/' => '/useful-information/pravilnaya-ustanovka-plastikovyh-okon-sekrety-zimnego-montazha/',
		'/posts/show/616-prichiny-produvaniya-plastikovogo-okna/' => '/useful-information/prichiny-produvaniya-plastikovogo-okna/',
		'/posts/show/556-prodazha-okon-po-nizkoy-stoimosti-pokupat-ili-net-/' => '/useful-information/prodazha-okon-po-nizkoy-stoimosti-pokupat-ili-net/',
		'/posts/show/570-proizvodstvo-plastikovyh-okon/' => '/useful-information/proizvodstvo-plastikovyh-okon/',
		'/posts/show/533-proizvodstvo-steklopaketov/' => '/useful-information/proizvodstvo-steklopaketov/',
		'/posts/show/545-provetrivanie-pomescheniya-s-plastikovymi-oknami/' => '/useful-information/provetrivanie-pomescheniya-s-plastikovymi-oknami/',
		'/posts/show/808-rasprodazha-gotovyh-pvh-okon-so-sklada-v-minske-/' => '/useful-information/rasprodazha-gotovyh-pvh-okon-so-sklada-v-minske/',
		'/posts/show/849-rasprodazha-okon-pvh-v-minske/' => '/useful-information/rasprodazha-okon-pvh-v-minske/',
		'/posts/show/549-rasprostranennye-mify-o-pvh-oknah/' => '/useful-information/rasprostranennye-mify-o-pvh-oknah/',
		'/posts/show/801-rasschitat-stoimost-okon-pvh-v-minske-raschet-tseny-na-plastikovye-okna/' => '/useful-information/rasschitat-stoimost-okon-pvh-v-minske-raschet-tseny-na-plastikovye-okna/',
		'/posts/show/rassrochka-na-okna-pvh-v-breste/' => '/useful-information/rassrochka-na-okna-pvh-v-breste/',
		'/posts/show/rassrochka-na-okna-pvh-v-ivacevichah/' => '/useful-information/rassrochka-na-okna-pvh-v-ivacevichah/',
		'/posts/show/rassrochka-na-okna-pvh-v-kobrine/' => '/useful-information/rassrochka-na-okna-pvh-v-kobrine/',
		'/posts/show/rassrochka-na-okna-pvh-v-marinoj-gorke/' => '/useful-information/rassrochka-na-okna-pvh-v-marinoj-gorke/',
		'/posts/show/rassrochka-na-okna-pvh-v-nesvizhe/' => '/useful-information/rassrochka-na-okna-pvh-v-nesvizhe/',
		'/posts/show/rassrochka-na-okna-pvh-v-pinske/' => '/useful-information/rassrochka-na-okna-pvh-v-pinske/',
		'/posts/show/rassrochka-na-okna-pvh-v-slucke/' => '/useful-information/rassrochka-na-okna-pvh-v-slucke/',
		'/posts/show/rassrochka-na-okna-v-vitebske/' => '/useful-information/rassrochka-na-okna-v-vitebske/',
		'/posts/show/546-regulirovka-okon-pvh/' => '/useful-information/regulirovka-okon-pvh/',
		'/posts/show/869-regulirovka-okon-pvh-v-minske-tsena-za-regulirovku-pvh-okon/' => '/useful-information/regulirovka-okon-pvh-v-minske-tsena-za-regulirovku-pvh-okon/',
		'/posts/show/825-regulirovka-steklopaketov-v-minske-tseny-na-regulirovku-steklopaketa/' => '/useful-information/regulirovka-steklopaketov-v-minske-tseny-na-regulirovku-steklopaketa/',
		'/posts/show/494-remont-okon-pvh-lyuboy-slozhnosti/' => '/useful-information/remont-okon-pvh-lyuboy-slozhnosti/',
		'/posts/show/497-remont-okon-pvh-lyuboy-slozhnosti/' => '/useful-information/remont-okon-pvh-lyuboy-slozhnosti/',
		'/posts/show/826-remont-okon-pvh-v-minske-tseny-na-remont-pvh-okon/' => '/useful-information/remont-okon-pvh-v-minske-tseny-na-remont-pvh-okon/',
		'/posts/show/529--roto-my-rabotaem-s-luchshimi/' => '/useful-information/roto-my-rabotaem-s-luchshimi/',
		'/posts/show/496-seychas-samoe-vremya-kupit-okna-/' => '/useful-information/seychas-samoe-vremya-kupit-okna/',
		'/posts/show/568-shumoizoliruyuschie-svoystva-steklopaketa/' => '/useful-information/shumoizoliruyuschie-svoystva-steklopaketa/',
		'/posts/show/skidki-na-okna-novoselam-v-minske/' => '/useful-information/skidki-na-okna-novoselam-v-minske/',
		'/posts/show/skidki-na-okna-pensioneram-v-minske/' => '/useful-information/skidki-na-okna-pensioneram-v-minske/',
		'/posts/show/664-sravnenie-steklopaketov-kakoy-vybrat/' => '/useful-information/sravnenie-steklopaketov-kakoy-vybrat/',
		'/posts/show/511-steklopaket-glavnyy-geroy-mira-plastikovyh-okon-/' => '/useful-information/steklopaket-glavnyy-geroy-mira-plastikovyh-okon/',
		'/posts/show/824-steklopakety-rehau-v-minske-tseny-na-rehau-steklopaket/' => '/useful-information/steklopakety-rehau-v-minske-tseny-na-rehau-steklopaket/',
		'/posts/show/834-steklopakety-v-rassrochku-v-minske-tseny-na-steklopakety-v-rassrochku/' => '/useful-information/steklopakety-v-rassrochku-v-minske-tseny-na-steklopakety-v-rassrochku/',
		'/posts/show/stoimost-okon-pvh-v-gorkah/' => '/useful-information/stoimost-okon-pvh-v-gorkah/',
		'/posts/show/815-stoimost-steklopaketov-v-minske-tseny-na-steklopakety/' => '/useful-information/stoimost-steklopaketov-v-minske-tseny-na-steklopakety/',
		'/posts/show/802-teploe-osteklenie-balkona-v-minske-tseny-na-teplye-ostekleniya/' => '/useful-information/teploe-osteklenie-balkona-v-minske-tseny-na-teplye-ostekleniya/',
		'/posts/show/735-teploe-osteklenie-dlya-kvartiry-v-minske/' => '/useful-information/teploe-osteklenie-dlya-kvartiry-v-minske/',
		'/posts/show/566-teplosberegayuschie-okna/' => '/useful-information/teplosberegayuschie-okna/',
		'/posts/show/659-tipichnye-oshibki-pri-vybore-plastikovyh-okon/' => '/useful-information/tipichnye-oshibki-pri-vybore-plastikovyh-okon/',
		'/posts/show/532-tseny-na-okna-pvh/' => '/useful-information/tseny-na-okna-pvh/',
		'/posts/show/493-ustanavlivay-okna-pvh-v-rassrochku-etoy-zimoy-za-rubli-bez-privyazki-k-kursu-/' => '/useful-information/ustanavlivay-okna-pvh-v-rassrochku-etoy-zimoy-za-rubli-bez-privyazki-k-kursu/',
		'/posts/show/750-ustanovit-okna-pvh-po-gostu-v-minske-tseny-na-montazh-okon-pvh-po-gostu/' => '/useful-information/ustanovit-okna-pvh-po-gostu-v-minske-tseny-na-montazh-okon-pvh-po-gostu/',
		'/posts/show/569-ustanovka-i-montazh-okon-pvh/' => '/useful-information/ustanovka-i-montazh-okon-pvh/',
		'/posts/show/ustanovka-okon-pvh-nedorogo/' => '/useful-information/ustanovka-okon-pvh-nedorogo/',
		'/posts/show/538-ustanovka-okon-pvh-zimoy-zimniy-montazh/' => '/useful-information/ustanovka-okon-pvh-zimoy-zimniy-montazh/',
		'/posts/show/567-ustanovka-plastikovyh-okon-v-chastnom-dome/' => '/useful-information/ustanovka-plastikovyh-okon-v-chastnom-dome/',
		'/posts/show/ustanovka-plastikovyh-okon-v-slucke/' => '/useful-information/ustanovka-plastikovyh-okon-v-slucke/',
		'/posts/show/ustanovka-plastikovyh-okon-v-vitebske/' => '/useful-information/ustanovka-plastikovyh-okon-v-vitebske/',
		'/posts/show/858-ustanovka-steklopaketov-v-minske-tsena-na-ustanovku-steklopaketov/' => '/useful-information/ustanovka-steklopaketov-v-minske-tsena-na-ustanovku-steklopaketov/',
		'/posts/show/652-vidy-moskitnyh-setok/' => '/useful-information/vidy-moskitnyh-setok/',
		'/posts/show/534-vidy-razdvizhnyh-balkonnyh-ram/' => '/useful-information/vidy-razdvizhnyh-balkonnyh-ram/',
		'/posts/show/551-vidy-razdvizhnyh-balkonnyh-ram/' => '/useful-information/vidy-razdvizhnyh-balkonnyh-ram/',
		'/posts/show/550-v-kakoe-vremya-goda-luchshe-ustanavlivat-okna-pvh/' => '/useful-information/v-kakoe-vremya-goda-luchshe-ustanavlivat-okna-pvh/',
		'/posts/show/654-vokny-dlya-dachy/' => '/useful-information/vokny-dlya-dachy/',
		'/posts/show/513-voprosy-po-otkosam-/' => '/useful-information/voprosy-po-otkosam/',
		'/posts/show/520-vrag-ne-proydet-ili-chto-nuzhno-znat-o-moskitnoy-setke-/' => '/useful-information/vrag-ne-proydet-ili-chto-nuzhno-znat-o-moskitnoy-setke/',
		'/posts/show/526-vse-delo-v-podokonnike-/' => '/useful-information/vse-delo-v-podokonnike/',
		'/posts/show/665-vyb-raem-mask-tnuyu-setku/' => '/useful-information/vybiraem-maskitnuyu-setku/',
		'/posts/show/571-vybiraem-okno-na-kuhnyu/' => '/useful-information/vybiraem-okno-na-kuhnyu/',
		'/posts/show/499-vybiraem-okno-v-detskuyu-komnatu-/' => '/useful-information/vybiraem-okno-v-detskuyu-komnatu/',
		'/posts/show/622-vybor-okon-pvh-dlya-balkona/' => '/useful-information/vybor-okon-pvh-dlya-balkona/',
		'/posts/show/661-yak-demantavats-akno/' => '/useful-information/yak-demantavats-akno/',
		'/posts/show/638-yak-l-kv-davats-praduvanne-plastykavaga-akna/' => '/useful-information/yak-likvidavats-praduvanne-plastykavaga-akna/',
		'/posts/show/641-yak-vybrats-plastykavae-akno-dlya-dz-tsyachaga-pakoyu/' => '/useful-information/yak-vybrats-plastykavae-akno-dlya-dzitsyachaga-pakoyu/',
		'/posts/show/524-zabota-o-detyah-missiya-panoramy-/' => '/useful-information/zabota-o-detyah-missiya-panoramy/',
		'/posts/show/508-zachem-platit-bolshe-s-nami-vy-ekonomite-na-pokupke-okon-optom-27-/' => '/useful-information/zachem-platit-bolshe-s-nami-vy-ekonomite-na-pokupke-okon-optom/',
		'/posts/show/760-zakazat-energosberegayuschie-steklopakety-v-minske-tseny-na-energosberegayuschie-steklopakety/' => '/useful-information/zakazat-energosberegayuschie-steklopakety-v-minske-tseny-na-energosberegayuschie-steklopakety/',
		'/posts/show/748-zakazat-frantsuzskoe-osteklenie-balkona-v-minske/' => '/useful-information/zakazat-frantsuzskoe-osteklenie-balkona-v-minske/',
		'/posts/show/765-zakazat-montazh-okon-pvh-v-minske-tseny-na-montazh-plastikovyh-okon/' => '/useful-information/zakazat-montazh-okon-pvh-v-minske-tseny-na-montazh-plastikovyh-okon/',
		'/posts/show/762-zakazat-montazh-steklopaketov-v-minske-tseny-na-remont-steklopaketa/' => '/useful-information/zakazat-montazh-steklopaketov-v-minske-tseny-na-remont-steklopaketa/',
		'/posts/show/749-zakazat-okna-pvh-po-gostu-v-minske-tseny-na-okna-pvh-gost/' => '/useful-information/zakazat-okna-pvh-po-gostu-v-minske-tseny-na-okna-pvh-gost/',
		'/posts/show/823-zakazat-okna-pvh-rehau-v-minske-tseny-na-okna-rehau-na-aktsii-/' => '/useful-information/zakazat-okna-pvh-rehau-v-minske-tseny-na-okna-rehau-na-aktsii/',
		'/posts/show/822-zakazat-okna-pvh-v-nesvizhe-tseny-na-okna-pvh-/' => '/useful-information/zakazat-okna-pvh-v-nesvizhe-tseny-na-okna-pvh/',
		'/posts/show/746-zakazat-osteklenie-balkonov-i-lodzhiy-v-minske-tseny-na-osteklenie-balkonov-i-lodzhiy/' => '/useful-information/zakazat-osteklenie-balkonov-i-lodzhiy-v-minske-tseny-na-osteklenie-balkonov-i-lodzhiy/',
		'/posts/show/788-zakazat-panoramnye-okna-v-minske-tseny/' => '/useful-information/zakazat-panoramnye-okna-v-minske-tseny/',
		'/posts/show/787-zakazat-plastikovye-okna-dlya-doma-v-minske/' => '/useful-information/zakazat-plastikovye-okna-dlya-doma-v-minske/',
		'/posts/show/789-zakazat-pvh-okna-ot-proizvoditelya-v-belarusi-tseny/' => '/useful-information/zakazat-pvh-okna-ot-proizvoditelya-v-belarusi-tseny/',
		'/posts/show/759-zakazat-razdvizhnye-steklopakety-v-minske-tseny-na-razdvizhnye-steklopakety/' => '/useful-information/zakazat-razdvizhnye-steklopakety-v-minske-tseny-na-razdvizhnye-steklopakety/',
		'/posts/show/747-zakazat-steklopakety-na-balkon-v-minske-tseny-na-steklopakety-na-balkon/' => '/useful-information/zakazat-steklopakety-na-balkon-v-minske-tseny-na-steklopakety-na-balkon/',
		'/posts/show/772-zakazat-teploe-ili-holodnoe-osteklenie-balkona-v-minske/' => '/useful-information/zakazat-teploe-ili-holodnoe-osteklenie-balkona-v-minske/',
		'/posts/show/761-zakazat-tonirovannye-steklopakety-v-minske-tseny-na-tonirovannye-steklopakety/' => '/useful-information/zakazat-tonirovannye-steklopakety-v-minske-tseny-na-tonirovannye-steklopakety/',
		'/posts/show/763-zakazat-zamenu-steklopaketov-v-plastikovom-okne-v-minske-tseny-na-zamenu-steklopaketa/' => '/useful-information/zakazat-zamenu-steklopaketov-v-plastikovom-okne-v-minske-tseny-na-zamenu-steklopaketa/',
		'/posts/show/859-zamena-stekla-v-steklopakete-v-minske-tsena-na-zamenu-stekla-v-steklopakete/' => '/useful-information/zamena-stekla-v-steklopakete-v-minske-tsena-na-zamenu-stekla-v-steklopakete/',
		'/posts/show/522-zamer-mikroklimata-unikalnoe-predlozhenie-ot-panoramy-/' => '/useful-information/zamer-mikroklimata-unikalnoe-predlozhenie-ot-panoramy/',
		'/posts/show/525-znakomtes-steklopaket-/' => '/useful-information/znakomtes-steklopaket/',
		'/posts/show/535-zvukoizolyatsiya-okon-pvh-svoimi-rukami/' => '/useful-information/zvukoizolyatsiya-okon-pvh-svoimi-rukami/',
		'/posts/show/870-kupit-gotovye-okna-pvh-v-minske-tsena-na-gotovye-plastikovye-okna/' => '/useful-information/kupit-gotovye-okna-pvh-v-minske-tsena-na-gotovye-plastikovye-okna/',
		'/okna_v_rassrochku/' => '/installment-plan/',
		'/nustanovka-plastikovyh-okon-v-chastnom-dome/' => '/windows-private-house/',
		'/novogodnyaya-rasprodazha/' => '/promotions/',
		'/fevralskaja-rasprodazha/' => '/promotions/',
		'/main_prew/' => '/',
		'/laminir-profil-pvh/' => '/laminated-windows/',
		'/kupit-okna-pvh-v-bobruyske/' => '/contacts/',
		'/funkcii-furnitury/' => '/hardware-siegenia/',
		'/about_company/' => '/about/',
		'/about/prodaja_okon_panorama/' => '/about/',
		'/step-2/' => '/',
		'/steklopakety/' => '/glazing/',
		'/rogoch-v/' => '/contacts/',
		'/provetrivanie_pomeshhenija_s_plastikovymi_oknami/' => '/plastic-windows/',
		'/prod/profil/' => '/plastic-windows/',
		'/prod/' => '/plastic-windows/',
		'/albinos/' => '/windows-albinos/',
		'/albinosy_sever/' => '/windows-albinos/',
		'/raspashnie_sistemi/' => '/windows-balcony/',
		'/razdvijnie_sistemi/' => '/windows-balcony/',
		'/okno_v_spalne/' => '/windows-bedroom/',
		'/okno-v-spalne-dve-stvorki/' => '/windows-bedroom/',
		'/vihod_na_balkon/' => '/windows-hall/',
		'/vyhod-na-balkon-dve-stvorki/' => '/windows-hall/',
		'/okno_na_kuhne/' => '/windows-kitchen/',
		'/okno-na-kuhne-dve-stvorki/' => '/windows-kitchen/'
	];

	if(in_array($sUrl, array_keys($ar301)) && !empty($sUrl)) {
		$sUrl = $ar301[$sUrl];
		$redirectSeo = $sUrl;
		$redirect = true;
	}
	
	if(!($_SERVER["HTTPS"]) || $_SERVER["HTTPS"] != "on") {
		$protocolChange = true;
		$redirect = true;
	}

	$sUrl = $_SERVER["REQUEST_URI"];
	if (!empty($_SERVER["QUERY_STRING"])) {
		$sUrl = str_replace("?" . $_SERVER["QUERY_STRING"], "", $_SERVER["REQUEST_URI"]);
	}

	if (
		(strpos($_SERVER["HTTP_HOST"], "www.") !== false) ||
		(strpos($_SERVER["HTTP_HOST"], "WWW.") !== false) ||
		!preg_match("/^(.*)\/$/", $sUrl) && !preg_match("/[.](.){2,5}$/", $sUrl) ||
		(preg_match("/^(.*)(index.php|index.html)$/", $sUrl)) ||
		(preg_match("/\/{2,}/", $sUrl)) ||
		$sUrl !== strtolower($sUrl)
	) {

		if (preg_match("/^(.*)(index.php|index.html)$/", $sUrl)) {
			$sUrl = preg_replace("/index.php(\/)?$/", "", $sUrl);
			$sUrl = preg_replace("/index.html(\/)?$/", "", $sUrl);
			$redirect = true;
			$dopRedirect = $sUrl;
		}
		if (preg_match("/\/{2,}/", $sUrl)) {
			$sUrl = preg_replace("/\/{2,}/", "/", $sUrl);
			$redirect = true;
			$dopRedirect = $sUrl;
		}
		if (!preg_match("/^(.*)\/$/", $sUrl) && !preg_match("/[.](.){2,5}$/", $sUrl)) {
			$sUrl .= "/";
			$redirect = true;
			$dopRedirect = $sUrl;
		}
		
		if($sUrl !== strtolower($sUrl)) {
			$sUrl = strtolower($sUrl);
			$redirect = true;
			$dopRedirect = $sUrl;
		}
		
		if((strpos($_SERVER["HTTP_HOST"], "www.") !== false) ||
		(strpos($_SERVER["HTTP_HOST"], "WWW.") !== false)) {
			$redirect = true;
			$dopRedirect = $sUrl;
		}
	}
	
	if($redirect === true) {
		if(!empty($redirectSeo)) {
			$sUrl = "https://oknapanorama.by" . $redirectSeo;
			if (!empty($_SERVER["QUERY_STRING"])) {
				$sUrl .= "?" . $_SERVER["QUERY_STRING"];
			}
			header("HTTP/1.1 301 Moved Permanently");
			header("Location: $sUrl");
			die();
		} elseif ($dopRedirect == false && $protocolChange == true) {
			$sUrl = "https://oknapanorama.by" . $_SERVER["REQUEST_URI"];
			header("HTTP/1.1 301 Moved Permanently");
			header("Location: $sUrl");
			die();
		} elseif($dopRedirect == true) {
			$sUrl = "https://oknapanorama.by" . $dopRedirect;
			if (!empty($_SERVER["QUERY_STRING"])) {
				$sUrl .= "?" . $_SERVER["QUERY_STRING"];
			}
			header("HTTP/1.1 301 Moved Permanently");
			header("Location: $sUrl");
			die();
		}
	}
}
?>